### PR TITLE
Reverted app code change

### PR DESCRIPTION
**Pull request by cvc1989**
This change wasn't needed.  We could have just added it to kaizen.php in Common2 and testing.php

### CODE REVIEW

**Comment by nkrantz23** [comment]
@cvc1989 whats this for?

**Comment by cvc1989** [comment]
@nkrantz23 - the new client/admin psr4 packages.  the code is bootstrapped in kaizen and we didnt need to load it in the framework. this branch removes the framework loading.

**Comment by nkrantz23** [comment]
@cvc1989 can we merge it?

**Comment by cvc1989** [comment]
@nkrantz23 - I'll just give it a quick test first

**Comment by nkrantz23** [comment]
@cvc1989 can we remove this function too? loadAppCode()

**Comment by cvc1989** [comment]
it's working fine. there aren't any issues.  merging.

**Pull request merged**
